Repository viur-framework/server, pull requests merged in 2018-09, with the labels that each got.

#93 Fix/spatial bone syntax
  bones/spatialBone.py
Labels: bug

#92 Correctly log the exception caught when raising an 500 Server-Error...
  __init__.py
Labels: enhancement

#91 Correctly handle an unset property in stringBone:getSearchDocumentFields
  bones/stringBone.py
Labels: bug

#90 Allow usage of None as value in Query().filter(), which is a valid type in datastore
  db.py
Labels: enhancement

#89 Handle malformed searchqueries in db.py
  db.py
Labels: enhancement

#88 Set bone uid to not required
  modules/user.py
Labels: bug

#87 Call doCleanupDeletedFiles and doDeleteWeakReferences deferred
  modules/file.py
Labels: bug

#80 Prevent two words from being stuffed together if we remove an invalid…
  bones/textBone.py
Labels: bug

#63 Fixing Jinja default templates to work with new selectBone
  template/editform_bone_select.html
  template/editform_bone_selectmulti.html
  template/editform_bone_selectone.html
Labels: bug

#96 Fixed #75: Sorting a stringBone(caseSensitive=False) via a relational…
  bones/relationalBone.py
Labels: bug

#95 Upgraded captchaBone to recaptcha2
  bones/captchaBone.py
  render/html/default.py
Labels: bug, enhancement

#86 cropping unwanted values on dateBone serialization
  CHANGELOG.md
  bones/dateBone.py
Labels: bug, hotfix
