Repository viur-framework/server, pull requests merged in 2018-11, with the labels that each got.

#98 Fixed signature of serialize() in randomSliceBone
  bones/randomSliceBone.py
Labels: bug

#102 Allow to select multiple kinds in DB import/export
  dbtransfer.py
Labels: enhancement, v2.4

#112 Added missing default template for captcha-bone
  template/editform_bone_captcha.html
Labels: bug

#83 Removing unnecessary debug from skeleton.py
  skeleton.py
Labels: v2.4

#82 relationalBone: Check for bone in postSavedHandler
  bones/relationalBone.py
Labels: bug, v2.4
