Repository viur-framework/server, pull requests merged in 2019-04, with the labels that each got.

#152 found and fixed a regression
  template/editform_bone_select.html
Labels: bug, v2.4

#151 Unwrap the first dictionary access in fileBone:unserialize
  bones/fileBone.py
Labels: enhancement, v2.4

#106 Allow definition of skeletons outside the skeleton folder
  __init__.py
  config.py
  skeleton.py
Labels: discussion, enhancement, v2.4

#153 Merge hotfixes from master back to develop
  __init__.py
  config.py
  db.py
  skeleton.py
Labels: v2.4

#149 Feature/summernote
  bones/textBone.py
Labels: enhancement

#150 Suggesting removal of obsolete drive_video standard module
  modules/drive_video.py
Labels: discussion, v2.4

#160 returning None on valid required value in baseBone.fromClient
  bones/bone.py
Labels: bug, v2.4

#159 Suitable bugfix for #48
  modules/user.py
  render/html/user.py
Labels: enhancement, v2.4

#157 removing old .value notation for bone value access
  CHANGELOG.md
  modules/order.py
Labels: hotfix, v2.4
