Repository viur-framework/server, pull requests merged in 2019-03, with the labels that each got.

#140 fixed some "available" typos
  bones/relationalBone.py
  bones/stringBone.py
  db.py
  render/__init__.py
Labels: typo, v2.4

#146 list instance-check in db.py
  db.py
Labels: bug, hotfix, v2.4

#145 removed unused, commented and broken Google checkout module.
  modules/order_googlecheckout.py
Labels: proposal, v2.4

#143 polished code
  bones/bone.py
  bones/captchaBone.py
  bones/numericBone.py
  bones/randomSliceBone.py
  bones/relationalBone.py
  bones/selectBone.py
  bones/spatialBone.py
  bones/textBone.py
  cache.py
  config.py
  db.py
  dbtransfer.py
  errors.py
  indexes.py
  languages/__init__.py
  languages/de.py
  languages/en.py
  modules/__init__.py
  modules/drive_video.py
  modules/order.py
  modules/order_paypal.py
  modules/order_sofort.py
  modules/page.py
  modules/user.py
  prototypes/__init__.py
  prototypes/tree.py
  render/__init__.py
  render/html/__init__.py
  render/html/default.py
  render/html/env/__init__.py
  render/html/env/viur.py
  render/vi/default.py
  securityheaders.py
  securitykey.py
  skeleton.py
  tasks.py
  utils.py
Labels: enhancement, proposal, typo, v2.4

#134 dimensions in refKeys and refresh task
  bones/fileBone.py
  modules/file.py
Labels: enhancement, v2.4

#139 Allow In Test on ListWrapper
  render/html/default.py
  render/html/wrap.py
Labels: v2.4

#147 Provide better debugging info in case a noRetry task failed.
  tasks.py
Labels: enhancement, v2.4

#138 Removing bugsnag and all related parts from ViUR
  __init__.py
  config.py
  libs/bugsnag.zip
Labels: proposal, v2.4

#103 Hotfixes the dbtransfer/upload to correctly obtain the oldBlobKey
  dbtransfer.py
  modules/file.py
Labels: bug, v2.4

#136 fixed emailRecipientOverride in sendMail
  utils.py
Labels: enhancement, hotfix, v2.4

#142 updated changelog
  CHANGELOG.md
Labels: enhancement, proposal, v2.4

#111 Fix skeleton.toDB.txnUpdate
  skeleton.py
Labels: discussion, proposal, v2.4
