Repository viur-framework/server, pull requests merged in 2019-12, with the labels that each got.

#197 improved error logging when building sorting filters for relationalBo…
  CHANGELOG.md
  bones/relationalBone.py
Labels: enhancement, v2.6

#193 Fixed wrongly raised Exception
  CHANGELOG.md
  db.py
Labels: bug, v2.6

#191 Made it possible to run deferred tasks on the index module
  CHANGELOG.md
  tasks.py
Labels: bug, proposal, v2.6

#198 Correctly process `error.Redirect` exceptions
  CHANGELOG.md
  __init__.py
  errors.py
Labels: bug, v2.6
