Repository viur-framework/server, pull requests merged in 2019-01, with the labels that each got.

#119 Fixing relationalBone.refresh()
  bones/relationalBone.py
Labels: bug, v2.4

#128 Fix date bone visible if magic
  bones/dateBone.py
Labels: discussion, v2.4

#123 unified templates, removed camelcase, errorpage improved
  resources/js/viur-forms.js
  template/editform_bone_bone.html
  template/editform_bone_bool.html
  template/editform_bone_captcha.html
  template/editform_bone_color.html
  template/editform_bone_date.html
  template/editform_bone_numeric.html
  template/editform_bone_password.html
  template/editform_bone_relational.treeitem.file.html
  template/editform_bone_select.html
  template/editform_bone_str.html
  template/editform_bone_text.html
  template/editform_category.html
  template/editform_row.html
  template/error.html
Labels: enhancement, v2.4
