Repository viur-framework/server, pull requests merged in 2019-02, with the labels that each got.

#130 Remove pytz
  libs/pytz.zip
Labels: v2.4

#133 Added a new _queue Paramater to deferred calls
  tasks.py
Labels: enhancement, v2.4

#135 changed year to 2019 and use https in url of viur.is
  README.md
  __init__.py
Labels: enhancement, v2.4

#132 conf["forceSSL"] = True by default?
  config.py
Labels: v2.4

#129 Limit the timewindow for second factor to 10 minutes
  modules/user.py
Labels: enhancement, security, v2.4
