Repository viur-framework/server, pull requests merged in 2019-05, with the labels that each got.

#161 changed behavior of non-image files in upload method of file module
  CHANGELOG.md
  modules/file.py
Labels: enhancement, v2.5

#156 Make sure that skeletons/ is explicitly imported at some place
  __init__.py
Labels: bug, discussion, v2.5

#162 Entries fetched with db.GetOrInsert and written with db.Put will now correctly flush the memcache
  CHANGELOG.md
  db.py
Labels: bug, v2.4

#155 Allow empty date setting to dateBone
  CHANGELOG.md
  bones/dateBone.py
Labels: bug, v2.4

#166 linked version diffs correctly in changelog
  CHANGELOG.md
Labels: v2.4

#167 Feature/fix minimum spatial guaranteed correctness
  CHANGELOG.md
  bones/spatialBone.py
Labels: bug
